#include "MPCNS_Pre_CubicGridGenerator.h"

#include <cerrno>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>

namespace
{
int GetIntOrDefault(Param &param, const std::string &name, int default_value)
{
    return param.HasInt(name) ? param.GetInt(name) : default_value;
}

double GetDoubleOrDefault(Param &param, const std::string &name, double default_value)
{
    return param.HasDou(name) ? param.GetDou(name) : default_value;
}

std::string GetStringOrDefault(Param &param, const std::string &name, const std::string &default_value)
{
    return param.HasStr(name) ? param.GetStr(name) : default_value;
}

void EnsureInputDirectory()
{
    if (mkdir("INPUT", 0755) != 0 && errno != EEXIST)
    {
        std::cout << "#Error Writing: can't create directory : \tINPUT" << std::endl;
        exit(-1);
    }
}

void WriteGridFile(const std::string &filename, int nx, int ny, int nz,
                   double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
{
    std::ofstream file(filename.c_str(), std::ios_base::out);
    if (!file)
    {
        std::cout << "#Error Writing: can't open file : \t" << filename << std::endl;
        exit(-1);
    }

    file << std::setprecision(16);
    file << 1 << "\n";
    file << nx << "\t" << ny << "\t" << nz << "\n";

    for (int k = 0; k < nz; ++k)
        for (int j = 0; j < ny; ++j)
            for (int i = 0; i < nx; ++i)
            {
                const double ratio = (nx == 1) ? 0.0 : static_cast<double>(i) / static_cast<double>(nx - 1);
                file << xmin + (xmax - xmin) * ratio << "\n";
            }

    for (int k = 0; k < nz; ++k)
        for (int j = 0; j < ny; ++j)
            for (int i = 0; i < nx; ++i)
            {
                const double ratio = (ny == 1) ? 0.0 : static_cast<double>(j) / static_cast<double>(ny - 1);
                file << ymin + (ymax - ymin) * ratio << "\n";
            }

    for (int k = 0; k < nz; ++k)
        for (int j = 0; j < ny; ++j)
            for (int i = 0; i < nx; ++i)
            {
                const double ratio = (nz == 1) ? 0.0 : static_cast<double>(k) / static_cast<double>(nz - 1);
                file << zmin + (zmax - zmin) * ratio << "\n";
            }
}

void WriteBoundaryNameFile(const std::string &filename)
{
    std::ofstream file(filename.c_str(), std::ios_base::out);
    if (!file)
    {
        std::cout << "#Error Writing: can't open file : \t" << filename << std::endl;
        exit(-1);
    }

    file << "FVBND 1 3\n";
    file << "No_Boundary_Condition\n";
    file << "Solid_Surface\n";
    file << "Symmetry\n";
    file << "Farfield\n";
    file << "Inflow\n";
    file << "Outflow\n";
    file << "Pole\n";
    file << "Generic_#1\n";
    file << "Generic_#2\n";
    file << "Generic_#3\n";
    file << "PERIOD-X\n";
    file << "period_X\n";
    file << "PERIOD-Y\n";
    file << "period_Y\n";
    file << "PERIOD-Z\n";
    file << "period_Z\n";
    file << "BOUNDARIES\n";
}

void WriteInpFile(const std::string &filename, int nx, int ny, int nz, const std::string &block_name)
{
    std::ofstream file(filename.c_str(), std::ios_base::out);
    if (!file)
    {
        std::cout << "#Error Writing: can't open file : \t" << filename << std::endl;
        exit(-1);
    }

    file << "# cubic periodic single-block inp generated by MPCNS preprocess\n";
    file << 1 << "\n";
    file << nx << "\t" << ny << "\t" << nz << "\t" << block_name << "\n";
    file << 6 << "\n";
    file << 1 << "\t" << 1 << "\t" << 1 << "\t" << ny << "\t" << 1 << "\t" << nz << "\t" << 11 << "\n";
    file << nx << "\t" << nx << "\t" << 1 << "\t" << ny << "\t" << 1 << "\t" << nz << "\t" << 12 << "\n";
    file << 1 << "\t" << nx << "\t" << 1 << "\t" << 1 << "\t" << 1 << "\t" << nz << "\t" << 13 << "\n";
    file << 1 << "\t" << nx << "\t" << ny << "\t" << ny << "\t" << 1 << "\t" << nz << "\t" << 14 << "\n";
    file << 1 << "\t" << nx << "\t" << 1 << "\t" << ny << "\t" << 1 << "\t" << 1 << "\t" << 15 << "\n";
    file << 1 << "\t" << nx << "\t" << 1 << "\t" << ny << "\t" << nz << "\t" << nz << "\t" << 16 << "\n";
}
} // namespace

bool CubicPeriodicGridGenerator::IsEnabled(Param &param)
{
    return param.HasBoo("generate_cubic_periodic_grid") && param.GetBoo("generate_cubic_periodic_grid");
}

void CubicPeriodicGridGenerator::GenerateIfEnabled(Param &param)
{
    if (!IsEnabled(param))
        return;

    const int nx = GetIntOrDefault(param, "cubic_nx", 9);
    const int ny = GetIntOrDefault(param, "cubic_ny", 9);
    const int nz = GetIntOrDefault(param, "cubic_nz", 9);
    if (nx < 2 || ny < 2 || nz < 2)
    {
        std::cout << "#Fatal Error: cubic_nx/cubic_ny/cubic_nz must be >= 2 for periodic faces." << std::endl;
        exit(-1);
    }

    const double xmin = GetDoubleOrDefault(param, "cubic_xmin", 0.0);
    const double xmax = GetDoubleOrDefault(param, "cubic_xmax", 1.0);
    const double ymin = GetDoubleOrDefault(param, "cubic_ymin", 0.0);
    const double ymax = GetDoubleOrDefault(param, "cubic_ymax", 1.0);
    const double zmin = GetDoubleOrDefault(param, "cubic_zmin", 0.0);
    const double zmax = GetDoubleOrDefault(param, "cubic_zmax", 1.0);
    const std::string block_name = GetStringOrDefault(param, "cubic_block_name", "Fluid");

    EnsureInputDirectory();
    WriteGridFile(param.GetStr("gfilename"), nx, ny, nz, xmin, xmax, ymin, ymax, zmin, zmax);
    WriteInpFile(param.GetStr("bfilename"), nx, ny, nz, block_name);
    WriteBoundaryNameFile(param.GetStr("ffilename"));

    param.AddParam("grd_readtype", 0);
    param.AddParam("dimension", 3);

    if (!param.HasBoo("if_split_group_info"))
        param.AddParam("if_split_group_info", false);

    std::cout << "\t-->Cubic periodic test grid has been generated in ./INPUT ! ! !\n";
}
